on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: lithier94675/lithier94675
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: profile
      - run: |
          cp index.md profile/README.md
          cd profile
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || ( git commit -m "update profile from workflow" && git push origin main )
